version: '3.8'

services:
  find-jav-bot:
    build: .
    container_name: find-jav-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ROBOT_NAME=${ROBOT_NAME:-Find-Jav-Bot}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-10000}
      - REQUEST_RETRIES=${REQUEST_RETRIES:-3}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 